apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-auto-build
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-auto-build
  template:
    metadata:
      labels:
        app: gitops-auto-build
    spec:
      containers:
        - name: gitops-auto-build-pods
          image: nginx:1.26
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
